### ISSUE TITLE
PR: Add support for `eslint-plugin-flowtype-errors`

### ISSUE THREAD

**Issue by amilajack** [traveloka/marlint#4]
This plugin reports flow errors as ESLint errors.

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

Note: In this demo, I am using atom with the packages 'linter' and 'linter-eslint'

https://github.com/amilajack/eslint-plugin-flowtype-errors

Would a PR for this be welcome?

**Comment by pveyes** [comment]
Hi @amilajack thanks for sharing this, this is really cool

We're moving our linter-related packages to monorepo in [traveloka/javascript](https://github.com/traveloka/javascript). Could you make a PR there instead?

**Comment by amilajack** [comment]
Sure thing!
